concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Runner 2.0"
  url = "https://git.fhict.nl"
  id = 10215
  token = "glrt-UrXnz1bFbX_9FBdjidVy"
  token_obtained_at = 2024-09-20T11:39:37Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
