name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build, Test, Coverage (H2)
        run: |
          ./gradlew clean test jacocoTestReport --no-daemon \
            -Dspring.profiles.active=test \
            -Dspring.datasource.url="jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_UPPER=false" \
            -Dspring.datasource.driver-class-name=org.h2.Driver \
            -Dspring.jpa.database-platform=org.hibernate.dialect.H2Dialect \
            -Dspring.jpa.hibernate.ddl-auto=update

      - name: SonarQube Analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar --no-daemon \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.token=${SONAR_TOKEN}

  docker:
    needs: build-test-analyze
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        if: ${{ secrets.REGISTRY && secrets.REGISTRY_USERNAME && secrets.REGISTRY_PASSWORD && secrets.IMAGE_NAME }}
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker Image
        if: ${{ secrets.REGISTRY && secrets.IMAGE_NAME }}
        run: |
          docker build -t ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .
          docker tag  ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Push Docker Image
        if: ${{ secrets.REGISTRY && secrets.IMAGE_NAME }}
        run: |
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

